#!/usr/bin/env sh
# ________       ___    ___ ___  ___  ___  __    ________     
# |\   ____\     |\  \  /  /|\  \|\  \|\  \|\  \ |\   ___ \    
# \ \  \___|_    \ \  \/  / | \  \\\  \ \  \/  /|\ \  \_|\ \   
# \ \_____  \    \ \    / / \ \   __  \ \   ___  \ \  \ \\ \  
#  \|____|\  \    /     \/   \ \  \ \  \ \  \\ \  \ \  \_\\ \ 
#    ____\_\  \  /  /\   \    \ \__\ \__\ \__\\ \__\ \_______\
#   |\_________\/__/ /\ __\    \|__|\|__|\|__| \|__|\|_______|
#   \|_________||__|/ \|__|                                   

# terminal emulator
super + {Return,t}
	kitty

# rofi
super + d
	rofi -show-icons -show drun

# sxhkd reload
super + Escape
	pkill -USR1 -x sxhkd

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {q,w}
	bspc node -{c,k}

############################## window states ################################
super + space
	bspc node -t {floating, tiled}

super + shift + p
	bspc node -t {pseudo_tiled, tiled}

super + f
	bspc node -t {fullscreen, tiled}

################################ focus/swap ################################# 

# focus/move the node in the given direction
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the next/previous window in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local.!hidden.window

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last


# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus/send to desktop
super + {_,shift + }{1-6,0}
	bspc {desktop -f,node -d} '^{1-6,6}'

################################ move/resize ################################ 

# expand a window by moving one of its side outward
super + alt + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {h,j,k,l}
	bspc node -v {-40 0,0 40,0 -40,40 0}

# powermenu
super + p
	$HOME/.config/polybar/colorblocks/scripts/powermenu.sh
	

######################## volume/brightness control ########################## 
XF86AudioLowerVolume
	amixer set Master 5%-
XF86AudioRaiseVolume
	amixer set Master 5%+
XF86AudioMute
	amixer set Master toggle

XF86MonBrightnessDown
	sudo xbacklight -dec 5
XF86MonBrightnessUp
	sudo xbacklight -inc 5

# lock screen
super + l
	betterlockscreen -l
